sudo: false
dist: trusty
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - re2c
    - python-dev
    - python-nose
    - python-numpy
script:
  - travis_wait 30 sh build-epics.sh -j2 </dev/null
  - ./build-testapp.sh
