sudo: false
dist: trusty
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - re2c
    - python-dev
    - python-nose
    - python-numpy
script: sh build-epics.sh -sj2 </dev/null
