sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - re2c
    - python-dev
    - python-nose
    - python-numpy
    - libgraphicsmagick++-dev
    - libhdf5-dev
    - libjpeg-dev
    - libnetcdf-dev
    - libtiff-dev
    - libz-dev

script:
  - travis_wait 30 sh build-epics.sh -j2 </dev/null
  - ./build-testapp.sh

jobs:
  include:
  - dist: xenial
  - dist: bionic

  - env: IMAGE=centos:8
    services: docker
    install: docker pull $IMAGE
    script: travis_wait 30 docker run --rm -v `pwd`:/io -w /io $IMAGE ./centos-build.sh

  - env: IMAGE=centos:7
    services: docker
    install: docker pull $IMAGE
    script: travis_wait 30 docker run --rm -v `pwd`:/io -w /io $IMAGE ./centos-build.sh
